name: Host Service CI
on:
  push:
    branches:
      - 'main'
    paths:
      - '*.js'
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1.Checkout
      uses: actions/checkout@v3

    - name: 2.Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 3.Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: dangtong/hostservice:${{ github.sha }}
    # steps:
    #   - uses: actions/checkout@v3
    #   - run: docker build -t dangtong/hostservice .
    #   - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    #     env:
    #       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   - run: docker push dangtong/hostservice
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - name: 1.Checkout
        uses: actions/checkout@v3
        with: 
          repository: 'dangtong76/hostservice-cd'
          token: ${{ secrets.GITHUB_TOKEN }}
          # path: 'main'
      - name: 2. Change Docker Tag
        run: |
          sed -i "s/image:\sdangtong\/node-app:.*/image:\sdangtong\/node-app:${{ github.sha }}/g" hostservice-dp.yaml
          git config --global user.email "dangtong@gmail.com"
          git config --global user.name "dangtong76"
          git commit -am "triggered by github action"
          git push origin main